//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.629.0 using the following command:
// XmlSchemaClassGenerator.Console xsd --pascal=no -nc
//
// Changed namespance to MameBuilder
// Removed references to 'Datafile.'
// Remove "http://tempuri.org/datafile" everywhere
// Annoyingly this app capitalises everything no matter what you do - if trying to get xsd.exe working then you'll have
// to rename everything, but since xsd.exe is a piece of crap I wouldn't bother.

namespace MameBuilder
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("mame", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("mame", Namespace="")]
    public partial class Mame
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Game> _game;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("game")]
        public System.Collections.ObjectModel.Collection<Game> Game
        {
            get
            {
                return this._game;
            }
            private set
            {
                this._game = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Mame" /> class.</para>
        /// </summary>
        public Mame()
        {
            this._game = new System.Collections.ObjectModel.Collection<Game>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("build")]
        public string Build { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private MameDebug _debug = MameDebug.No;
        
        [System.ComponentModel.DefaultValueAttribute(MameDebug.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("debug")]
        public MameDebug Debug
        {
            get
            {
                return this._debug;
            }
            set
            {
                this._debug = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("mameconfig")]
        public string Mameconfig { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("game", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("game", Namespace="")]
    public partial class Game
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("year")]
        public string Year { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("manufacturer")]
        public string Manufacturer { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Biosset> _biosset;
        
        [System.Xml.Serialization.XmlElementAttribute("biosset")]
        public System.Collections.ObjectModel.Collection<Biosset> Biosset
        {
            get
            {
                return this._biosset;
            }
            private set
            {
                this._biosset = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Biosset collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BiossetSpecified
        {
            get
            {
                return (this.Biosset.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Game" /> class.</para>
        /// </summary>
        public Game()
        {
            this._biosset = new System.Collections.ObjectModel.Collection<Biosset>();
            this._rom = new System.Collections.ObjectModel.Collection<Rom>();
            this._disk = new System.Collections.ObjectModel.Collection<Disk>();
            this._sample = new System.Collections.ObjectModel.Collection<Sample>();
            this._chip = new System.Collections.ObjectModel.Collection<Chip>();
            this._display = new System.Collections.ObjectModel.Collection<Display>();
            this._dipswitch = new System.Collections.ObjectModel.Collection<Dipswitch>();
            this._configuration = new System.Collections.ObjectModel.Collection<Configuration>();
            this._category = new System.Collections.ObjectModel.Collection<Category>();
            this._adjuster = new System.Collections.ObjectModel.Collection<Adjuster>();
            this._device = new System.Collections.ObjectModel.Collection<Device>();
            this._softwarelist = new System.Collections.ObjectModel.Collection<Softwarelist>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Rom> _rom;
        
        [System.Xml.Serialization.XmlElementAttribute("rom")]
        public System.Collections.ObjectModel.Collection<Rom> Rom
        {
            get
            {
                return this._rom;
            }
            private set
            {
                this._rom = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Rom collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RomSpecified
        {
            get
            {
                return (this.Rom.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Disk> _disk;
        
        [System.Xml.Serialization.XmlElementAttribute("disk")]
        public System.Collections.ObjectModel.Collection<Disk> Disk
        {
            get
            {
                return this._disk;
            }
            private set
            {
                this._disk = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Disk collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiskSpecified
        {
            get
            {
                return (this.Disk.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Sample> _sample;
        
        [System.Xml.Serialization.XmlElementAttribute("sample")]
        public System.Collections.ObjectModel.Collection<Sample> Sample
        {
            get
            {
                return this._sample;
            }
            private set
            {
                this._sample = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Sample collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SampleSpecified
        {
            get
            {
                return (this.Sample.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Chip> _chip;
        
        [System.Xml.Serialization.XmlElementAttribute("chip")]
        public System.Collections.ObjectModel.Collection<Chip> Chip
        {
            get
            {
                return this._chip;
            }
            private set
            {
                this._chip = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Chip collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChipSpecified
        {
            get
            {
                return (this.Chip.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Display> _display;
        
        [System.Xml.Serialization.XmlElementAttribute("display")]
        public System.Collections.ObjectModel.Collection<Display> Display
        {
            get
            {
                return this._display;
            }
            private set
            {
                this._display = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Display collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplaySpecified
        {
            get
            {
                return (this.Display.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("sound")]
        public Sound Sound { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("input")]
        public Input Input { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Dipswitch> _dipswitch;
        
        [System.Xml.Serialization.XmlElementAttribute("dipswitch")]
        public System.Collections.ObjectModel.Collection<Dipswitch> Dipswitch
        {
            get
            {
                return this._dipswitch;
            }
            private set
            {
                this._dipswitch = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Dipswitch collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DipswitchSpecified
        {
            get
            {
                return (this.Dipswitch.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Configuration> _configuration;
        
        [System.Xml.Serialization.XmlElementAttribute("configuration")]
        public System.Collections.ObjectModel.Collection<Configuration> Configuration
        {
            get
            {
                return this._configuration;
            }
            private set
            {
                this._configuration = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Configuration collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfigurationSpecified
        {
            get
            {
                return (this.Configuration.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Category> _category;
        
        [System.Xml.Serialization.XmlElementAttribute("category")]
        public System.Collections.ObjectModel.Collection<Category> Category
        {
            get
            {
                return this._category;
            }
            private set
            {
                this._category = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Category collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategorySpecified
        {
            get
            {
                return (this.Category.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Adjuster> _adjuster;
        
        [System.Xml.Serialization.XmlElementAttribute("adjuster")]
        public System.Collections.ObjectModel.Collection<Adjuster> Adjuster
        {
            get
            {
                return this._adjuster;
            }
            private set
            {
                this._adjuster = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Adjuster collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdjusterSpecified
        {
            get
            {
                return (this.Adjuster.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("driver")]
        public Driver Driver { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Device> _device;
        
        [System.Xml.Serialization.XmlElementAttribute("device")]
        public System.Collections.ObjectModel.Collection<Device> Device
        {
            get
            {
                return this._device;
            }
            private set
            {
                this._device = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Device collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceSpecified
        {
            get
            {
                return (this.Device.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Softwarelist> _softwarelist;
        
        [System.Xml.Serialization.XmlElementAttribute("softwarelist")]
        public System.Collections.ObjectModel.Collection<Softwarelist> Softwarelist
        {
            get
            {
                return this._softwarelist;
            }
            private set
            {
                this._softwarelist = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Softwarelist collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SoftwarelistSpecified
        {
            get
            {
                return (this.Softwarelist.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sourcefile")]
        public string Sourcefile { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private GameIsbios _isbios = GameIsbios.No;
        
        [System.ComponentModel.DefaultValueAttribute(GameIsbios.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("isbios")]
        public GameIsbios Isbios
        {
            get
            {
                return this._isbios;
            }
            set
            {
                this._isbios = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private GameRunnable _runnable = GameRunnable.Yes;
        
        [System.ComponentModel.DefaultValueAttribute(GameRunnable.Yes)]
        [System.Xml.Serialization.XmlAttributeAttribute("runnable")]
        public GameRunnable Runnable
        {
            get
            {
                return this._runnable;
            }
            set
            {
                this._runnable = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("cloneof")]
        public string Cloneof { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("romof")]
        public string Romof { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sampleof")]
        public string Sampleof { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("biosset", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("biosset", Namespace="")]
    public partial class Biosset
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private BiossetDefault _default = BiossetDefault.No;
        
        [System.ComponentModel.DefaultValueAttribute(BiossetDefault.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("default")]
        public BiossetDefault Default
        {
            get
            {
                return this._default;
            }
            set
            {
                this._default = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BiossetDefault", Namespace="", AnonymousType=true)]
    public enum BiossetDefault
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("rom", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("rom", Namespace="")]
    public partial class Rom
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("bios")]
        public string Bios { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("size")]
        public string Size { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("crc")]
        public string Crc { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("md5")]
        public string Md5 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sha1")]
        public string Sha1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("merge")]
        public string Merge { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("region")]
        public string Region { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("offset")]
        public string Offset { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private RomStatus _status = RomStatus.Good;
        
        [System.ComponentModel.DefaultValueAttribute(RomStatus.Good)]
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public RomStatus Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private RomOptional _optional = RomOptional.No;
        
        [System.ComponentModel.DefaultValueAttribute(RomOptional.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("optional")]
        public RomOptional Optional
        {
            get
            {
                return this._optional;
            }
            set
            {
                this._optional = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RomStatus", Namespace="", AnonymousType=true)]
    public enum RomStatus
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("baddump")]
        Baddump,
        
        [System.Xml.Serialization.XmlEnumAttribute("nodump")]
        Nodump,
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RomOptional", Namespace="", AnonymousType=true)]
    public enum RomOptional
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("disk", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("disk", Namespace="")]
    public partial class Disk
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("md5")]
        public string Md5 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sha1")]
        public string Sha1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("merge")]
        public string Merge { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("region")]
        public string Region { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("index")]
        public string Index { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DiskStatus _status = DiskStatus.Good;
        
        [System.ComponentModel.DefaultValueAttribute(DiskStatus.Good)]
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public DiskStatus Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DiskOptional _optional = DiskOptional.No;
        
        [System.ComponentModel.DefaultValueAttribute(DiskOptional.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("optional")]
        public DiskOptional Optional
        {
            get
            {
                return this._optional;
            }
            set
            {
                this._optional = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DiskStatus", Namespace="", AnonymousType=true)]
    public enum DiskStatus
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("baddump")]
        Baddump,
        
        [System.Xml.Serialization.XmlEnumAttribute("nodump")]
        Nodump,
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DiskOptional", Namespace="", AnonymousType=true)]
    public enum DiskOptional
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sample", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("sample", Namespace="")]
    public partial class Sample
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("chip", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("chip", Namespace="")]
    public partial class Chip
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("tag")]
        public string Tag { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public ChipType Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("clock")]
        public string Clock { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChipType", Namespace="", AnonymousType=true)]
    public enum ChipType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("cpu")]
        Cpu,
        
        [System.Xml.Serialization.XmlEnumAttribute("audio")]
        Audio,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("display", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("display", Namespace="")]
    public partial class Display
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public DisplayType Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("rotate")]
        public DisplayRotate Rotate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DisplayFlipx _flipx = DisplayFlipx.No;
        
        [System.ComponentModel.DefaultValueAttribute(DisplayFlipx.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("flipx")]
        public DisplayFlipx Flipx
        {
            get
            {
                return this._flipx;
            }
            set
            {
                this._flipx = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("width")]
        public string Width { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("height")]
        public string Height { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("refresh")]
        public string Refresh { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("pixclock")]
        public string Pixclock { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("htotal")]
        public string Htotal { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("hbend")]
        public string Hbend { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("hbstart")]
        public string Hbstart { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("vtotal")]
        public string Vtotal { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("vbend")]
        public string Vbend { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("vbstart")]
        public string Vbstart { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DisplayType", Namespace="", AnonymousType=true)]
    public enum DisplayType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("raster")]
        Raster,
        
        [System.Xml.Serialization.XmlEnumAttribute("vector")]
        Vector,
        
        [System.Xml.Serialization.XmlEnumAttribute("lcd")]
        Lcd,
        
        [System.Xml.Serialization.XmlEnumAttribute("unknown")]
        Unknown,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DisplayRotate", Namespace="", AnonymousType=true)]
    public enum DisplayRotate
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
        
        [System.Xml.Serialization.XmlEnumAttribute("180")]
        Item180,
        
        [System.Xml.Serialization.XmlEnumAttribute("270")]
        Item270,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DisplayFlipx", Namespace="", AnonymousType=true)]
    public enum DisplayFlipx
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sound", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("sound", Namespace="")]
    public partial class Sound
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("channels")]
        public string Channels { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("input", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("input", Namespace="")]
    public partial class Input
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Control> _control;
        
        [System.Xml.Serialization.XmlElementAttribute("control")]
        public System.Collections.ObjectModel.Collection<Control> Control
        {
            get
            {
                return this._control;
            }
            private set
            {
                this._control = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Control collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ControlSpecified
        {
            get
            {
                return (this.Control.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Input" /> class.</para>
        /// </summary>
        public Input()
        {
            this._control = new System.Collections.ObjectModel.Collection<Control>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private InputService _service = InputService.No;
        
        [System.ComponentModel.DefaultValueAttribute(InputService.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("service")]
        public InputService Service
        {
            get
            {
                return this._service;
            }
            set
            {
                this._service = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private InputTilt _tilt = InputTilt.No;
        
        [System.ComponentModel.DefaultValueAttribute(InputTilt.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("tilt")]
        public InputTilt Tilt
        {
            get
            {
                return this._tilt;
            }
            set
            {
                this._tilt = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("players")]
        public string Players { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("buttons")]
        public string Buttons { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("coins")]
        public string Coins { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("control", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("control", Namespace="")]
    public partial class Control
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("minimum")]
        public string Minimum { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("maximum")]
        public string Maximum { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sensitivity")]
        public string Sensitivity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("keydelta")]
        public string Keydelta { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ControlReverse _reverse = ControlReverse.No;
        
        [System.ComponentModel.DefaultValueAttribute(ControlReverse.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("reverse")]
        public ControlReverse Reverse
        {
            get
            {
                return this._reverse;
            }
            set
            {
                this._reverse = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ControlReverse", Namespace="", AnonymousType=true)]
    public enum ControlReverse
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InputService", Namespace="", AnonymousType=true)]
    public enum InputService
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InputTilt", Namespace="", AnonymousType=true)]
    public enum InputTilt
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dipswitch", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("dipswitch", Namespace="")]
    public partial class Dipswitch
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Dipvalue> _dipvalue;
        
        [System.Xml.Serialization.XmlElementAttribute("dipvalue")]
        public System.Collections.ObjectModel.Collection<Dipvalue> Dipvalue
        {
            get
            {
                return this._dipvalue;
            }
            private set
            {
                this._dipvalue = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Dipvalue collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DipvalueSpecified
        {
            get
            {
                return (this.Dipvalue.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Dipswitch" /> class.</para>
        /// </summary>
        public Dipswitch()
        {
            this._dipvalue = new System.Collections.ObjectModel.Collection<Dipvalue>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("tag")]
        public string Tag { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("mask")]
        public string Mask { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dipvalue", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("dipvalue", Namespace="")]
    public partial class Dipvalue
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DipvalueDefault _default = DipvalueDefault.No;
        
        [System.ComponentModel.DefaultValueAttribute(DipvalueDefault.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("default")]
        public DipvalueDefault Default
        {
            get
            {
                return this._default;
            }
            set
            {
                this._default = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DipvalueDefault", Namespace="", AnonymousType=true)]
    public enum DipvalueDefault
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("configuration", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("configuration", Namespace="")]
    public partial class Configuration
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Confsetting> _confsetting;
        
        [System.Xml.Serialization.XmlElementAttribute("confsetting")]
        public System.Collections.ObjectModel.Collection<Confsetting> Confsetting
        {
            get
            {
                return this._confsetting;
            }
            private set
            {
                this._confsetting = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Confsetting collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfsettingSpecified
        {
            get
            {
                return (this.Confsetting.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Configuration" /> class.</para>
        /// </summary>
        public Configuration()
        {
            this._confsetting = new System.Collections.ObjectModel.Collection<Confsetting>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("tag")]
        public string Tag { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("mask")]
        public string Mask { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("confsetting", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("confsetting", Namespace="")]
    public partial class Confsetting
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ConfsettingDefault _default = ConfsettingDefault.No;
        
        [System.ComponentModel.DefaultValueAttribute(ConfsettingDefault.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("default")]
        public ConfsettingDefault Default
        {
            get
            {
                return this._default;
            }
            set
            {
                this._default = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConfsettingDefault", Namespace="", AnonymousType=true)]
    public enum ConfsettingDefault
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("category", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("category", Namespace="")]
    public partial class Category
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Item> _item;
        
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public System.Collections.ObjectModel.Collection<Item> Item
        {
            get
            {
                return this._item;
            }
            private set
            {
                this._item = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Item collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemSpecified
        {
            get
            {
                return (this.Item.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Category" /> class.</para>
        /// </summary>
        public Category()
        {
            this._item = new System.Collections.ObjectModel.Collection<Item>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("item", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("item", Namespace="")]
    public partial class Item
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ItemDefault _default = ItemDefault.No;
        
        [System.ComponentModel.DefaultValueAttribute(ItemDefault.No)]
        [System.Xml.Serialization.XmlAttributeAttribute("default")]
        public ItemDefault Default
        {
            get
            {
                return this._default;
            }
            set
            {
                this._default = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemDefault", Namespace="", AnonymousType=true)]
    public enum ItemDefault
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("adjuster", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("adjuster", Namespace="")]
    public partial class Adjuster
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("default")]
        public string Default { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("driver", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("driver", Namespace="")]
    public partial class Driver
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public DriverStatus Status { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("emulation")]
        public DriverEmulation Emulation { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("color")]
        public DriverColor Color { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("sound")]
        public DriverSound Sound { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("graphic")]
        public DriverGraphic Graphic { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("cocktail")]
        public DriverCocktail Cocktail { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Cocktail property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CocktailSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("protection")]
        public DriverProtection Protection { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Protection property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProtectionSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("savestate")]
        public DriverSavestate Savestate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("palettesize")]
        public string Palettesize { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverStatus", Namespace="", AnonymousType=true)]
    public enum DriverStatus
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
        
        [System.Xml.Serialization.XmlEnumAttribute("imperfect")]
        Imperfect,
        
        [System.Xml.Serialization.XmlEnumAttribute("preliminary")]
        Preliminary,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverEmulation", Namespace="", AnonymousType=true)]
    public enum DriverEmulation
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
        
        [System.Xml.Serialization.XmlEnumAttribute("imperfect")]
        Imperfect,
        
        [System.Xml.Serialization.XmlEnumAttribute("preliminary")]
        Preliminary,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverColor", Namespace="", AnonymousType=true)]
    public enum DriverColor
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
        
        [System.Xml.Serialization.XmlEnumAttribute("imperfect")]
        Imperfect,
        
        [System.Xml.Serialization.XmlEnumAttribute("preliminary")]
        Preliminary,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverSound", Namespace="", AnonymousType=true)]
    public enum DriverSound
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
        
        [System.Xml.Serialization.XmlEnumAttribute("imperfect")]
        Imperfect,
        
        [System.Xml.Serialization.XmlEnumAttribute("preliminary")]
        Preliminary,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverGraphic", Namespace="", AnonymousType=true)]
    public enum DriverGraphic
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
        
        [System.Xml.Serialization.XmlEnumAttribute("imperfect")]
        Imperfect,
        
        [System.Xml.Serialization.XmlEnumAttribute("preliminary")]
        Preliminary,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverCocktail", Namespace="", AnonymousType=true)]
    public enum DriverCocktail
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
        
        [System.Xml.Serialization.XmlEnumAttribute("imperfect")]
        Imperfect,
        
        [System.Xml.Serialization.XmlEnumAttribute("preliminary")]
        Preliminary,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverProtection", Namespace="", AnonymousType=true)]
    public enum DriverProtection
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("good")]
        Good,
        
        [System.Xml.Serialization.XmlEnumAttribute("imperfect")]
        Imperfect,
        
        [System.Xml.Serialization.XmlEnumAttribute("preliminary")]
        Preliminary,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DriverSavestate", Namespace="", AnonymousType=true)]
    public enum DriverSavestate
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("supported")]
        Supported,
        
        [System.Xml.Serialization.XmlEnumAttribute("unsupported")]
        Unsupported,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("device", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("device", Namespace="")]
    public partial class Device
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Instance> _instance;
        
        [System.Xml.Serialization.XmlElementAttribute("instance")]
        public System.Collections.ObjectModel.Collection<Instance> Instance
        {
            get
            {
                return this._instance;
            }
            private set
            {
                this._instance = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Instance collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstanceSpecified
        {
            get
            {
                return (this.Instance.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Device" /> class.</para>
        /// </summary>
        public Device()
        {
            this._instance = new System.Collections.ObjectModel.Collection<Instance>();
            this._extension = new System.Collections.ObjectModel.Collection<Extension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<Extension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("tag")]
        public string Tag { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("mandatory")]
        public string Mandatory { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("interface")]
        public string Interface { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("instance", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("instance", Namespace="")]
    public partial class Instance
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("briefname")]
        public string Briefname { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("extension", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("extension", Namespace="")]
    public partial class Extension
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("softwarelist", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("softwarelist", Namespace="")]
    public partial class Softwarelist
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GameIsbios", Namespace="", AnonymousType=true)]
    public enum GameIsbios
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GameRunnable", Namespace="", AnonymousType=true)]
    public enum GameRunnable
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MameDebug", Namespace="", AnonymousType=true)]
    public enum MameDebug
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
}
